# Generated by Django 5.1.1 on 2025-10-20 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('quest', models.IntegerField()),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('attendance_count', models.IntegerField(default=0)),
                ('today_attended', models.BooleanField(default=False)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.characters')),
                ('completed_chapters', models.ManyToManyField(blank=True, related_name='completed_by_characters', to='main.chapter')),
                ('completed_quests', models.ManyToManyField(blank=True, related_name='completed_by_char_info', to='main.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'charInfo',
            },
        ),
    ]
