# Generated by Django 5.1.1 on 2024-11-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charinfo',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
