# Generated by Django 5.2.7 on 2025-10-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charinfo',
            old_name='classToken',
            new_name='exp',
        ),
        migrations.RenameField(
            model_name='charinfo',
            old_name='galeon',
            new_name='gold',
        ),
        migrations.RenameField(
            model_name='charinfo',
            old_name='searchDone',
            new_name='quest',
        ),
    ]
