# Generated by Django 5.1.1 on 2025-10-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charinfo',
            name='fishing_score',
            field=models.PositiveIntegerField(default=0, verbose_name='낚시 점수'),
        ),
    ]
