# Generated by Django 5.1.1 on 2024-11-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_charinfo_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='charinfo',
            name='attendance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charinfo',
            name='today_attended',
            field=models.BooleanField(default=False),
        ),
    ]
