# Generated by Django 5.1.1 on 2025-10-29 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_characters_charprofilemusic'),
        ('users', '0002_charinfo_fishing_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='던전 이름')),
                ('goal_distance', models.PositiveIntegerField(default=4000, verbose_name='목표 거리(m)')),
                ('current_distance', models.PositiveIntegerField(default=0, verbose_name='현재 누적 거리(m)')),
            ],
        ),
        migrations.AddField(
            model_name='charinfo',
            name='dungeon_b1_contribution',
            field=models.PositiveIntegerField(default=0, verbose_name='엘리시온 던전 B1 기여도(m)'),
        ),
        migrations.CreateModel(
            name='DungeonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='로그 제목')),
                ('action_description', models.TextField(blank=True, null=True, verbose_name='행동 지문')),
                ('distance_walked', models.PositiveIntegerField(default=0, verbose_name='걸은 거리(m)')),
                ('log_image', models.ImageField(blank=True, null=True, upload_to='dungeon_logs/', verbose_name='로그 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_logs', to='member.characters')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.dungeon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
