# Generated by Django 5.1.1 on 2025-11-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dungeon_charinfo_dungeon_b1_contribution_dungeonlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrapMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='함정/부상 메시지')),
            ],
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='current_distance',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='goal_distance',
        ),
        migrations.AddField(
            model_name='charinfo',
            name='dungeon_b3_contribution',
            field=models.PositiveIntegerField(default=0, verbose_name='던전 B3 기여도(성공 횟수)'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='current_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='현재 진행도(%)'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='goal_progress',
            field=models.PositiveIntegerField(default=100, verbose_name='목표 진행도(%)'),
        ),
        migrations.AddField(
            model_name='dungeonlog',
            name='was_successful',
            field=models.BooleanField(default=False, verbose_name='함정 통과 여부'),
        ),
        migrations.AlterModelTable(
            name='charinfo',
            table=None,
        ),
    ]
