# Generated by Django 5.1.1 on 2025-11-01 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_trapmessage_remove_dungeon_current_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.dungeonlog')),
            ],
        ),
    ]
