# Generated by Django 5.1.1 on 2025-11-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dungeoncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='charinfo',
            name='dungeon_b1_drakus_contribution',
            field=models.PositiveIntegerField(default=0, verbose_name='드라쿠스 B1 기여도(pt)'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='current_points',
            field=models.PositiveIntegerField(default=0, verbose_name='현재 누적 포인트'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='goal_points',
            field=models.PositiveIntegerField(default=1000000, verbose_name='목표 포인트'),
        ),
        migrations.AddField(
            model_name='dungeonlog',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='획득 포인트'),
        ),
    ]
