# Generated by Django 5.1.1 on 2025-11-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_charinfo_dungeon_b1_drakus_contribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterTrapMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='몬스터 반격/공격 실패 메시지')),
            ],
        ),
        migrations.AddField(
            model_name='charinfo',
            name='dungeon_b3_drakus_contribution',
            field=models.PositiveIntegerField(default=0, verbose_name='드라쿠스 B3 기여도(데미지)'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='current_damage_dealt',
            field=models.PositiveIntegerField(default=0, verbose_name='현재 누적 데미지'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='goal_hp',
            field=models.PositiveIntegerField(default=500000, verbose_name='보스 목표 HP'),
        ),
        migrations.AddField(
            model_name='dungeonlog',
            name='damage_dealt',
            field=models.PositiveIntegerField(default=0, verbose_name='가한 데미지'),
        ),
        migrations.AlterField(
            model_name='dungeonlog',
            name='was_successful',
            field=models.BooleanField(default=False, verbose_name='성공 여부 (B3 함정/B3 보스전)'),
        ),
    ]
