# Generated by Django 5.1.1 on 2025-10-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
                ('itemPrice', models.IntegerField()),
                ('itemShow', models.BooleanField()),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
                ('itemPrice', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
                ('recipe', models.TextField()),
                ('discovered', models.BooleanField()),
                ('discoverer', models.TextField(null=True)),
            ],
            options={
                'db_table': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemInfo', models.TextField()),
            ],
        ),
    ]
