# Generated by Django 5.1.1 on 2024-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemEngName', models.TextField()),
                ('itemImage', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
                ('itemPrice', models.IntegerField()),
                ('show', models.BooleanField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Item_magic',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemImage', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemType', models.TextField()),
                ('itemInfo', models.TextField()),
            ],
            options={
                'db_table': 'items_magic',
            },
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('potion', models.TextField()),
                ('potionInfo', models.TextField()),
                ('potionRecipe', models.TextField()),
                ('degree', models.IntegerField()),
                ('discovered', models.BooleanField()),
                ('discoverer', models.TextField(null=True)),
                ('price', models.IntegerField()),
                ('show', models.BooleanField()),
            ],
            options={
                'db_table': 'potion',
            },
        ),
    ]
