# Generated by Django 5.1.1 on 2025-10-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gacha',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemImage', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grinffindor', models.IntegerField(default=0)),
                ('hufflepuff', models.IntegerField(default=0)),
                ('ravenclaw', models.IntegerField(default=0)),
                ('slyderin', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'House',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemEngName', models.TextField()),
                ('itemImage', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
                ('itemPrice', models.IntegerField()),
                ('show', models.BooleanField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Item_magic',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemInfo', models.TextField()),
                ('itemDegree', models.IntegerField()),
                ('itemCategory', models.TextField()),
                ('itemCategory2', models.TextField()),
            ],
            options={
                'db_table': 'items_magic',
            },
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemInfo', models.TextField()),
                ('potionRecipe', models.TextField()),
                ('degree', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discovered', models.BooleanField()),
                ('discoverer', models.TextField(null=True)),
                ('itemCategory', models.TextField(default='마법 약')),
            ],
            options={
                'db_table': 'potion',
            },
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PotionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PotionStatus',
            },
        ),
    ]
