# Generated by Django 5.1.1 on 2024-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gacha',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemImage', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemInfo', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='item_magic',
            old_name='itemImage',
            new_name='itemCategory2',
        ),
        migrations.RenameField(
            model_name='item_magic',
            old_name='itemType',
            new_name='itemDegree',
        ),
        migrations.RemoveField(
            model_name='potion',
            name='show',
        ),
    ]
