# Generated by Django 5.1.1 on 2025-10-22 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_characters_charprofilemusic'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='물고기 이름')),
                ('grade', models.PositiveIntegerField(choices=[(1, '1등급'), (2, '2등급'), (3, '3등급')], verbose_name='등급')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='점수')),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='쓰레기 이름')),
            ],
        ),
        migrations.CreateModel(
            name='FishingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catch_description', models.CharField(max_length=200, verbose_name='낚시 결과 설명')),
                ('action_description', models.TextField(blank=True, null=True, verbose_name='행동 지문')),
                ('caught_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_logs', to='member.characters')),
            ],
            options={
                'ordering': ['-caught_at'],
            },
        ),
        migrations.CreateModel(
            name='FishingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.fishinglog')),
            ],
        ),
    ]
