# Generated by Django 5.1.1 on 2024-11-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cookie_gacha_scroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_magic',
            name='itemDegree',
            field=models.IntegerField(),
        ),
    ]
