# Generated by Django 5.2.7 on 2025-10-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_item_itemengname_remove_item_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='show',
        ),
    ]
