# Generated by Django 5.1.1 on 2025-11-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_fish_trash_fishinglog_fishingcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('gold', '골드 (G)'), ('exp', '경험치 (EXP)')], default='gold', max_length=10, verbose_name='화폐 종류'),
        ),
    ]
