# Generated by Django 5.1.1 on 2024-11-10 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_magic_itemdegree'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grinffindor', models.IntegerField(default=0)),
                ('hufflepuff', models.IntegerField(default=0)),
                ('ravenclaw', models.IntegerField(default=0)),
                ('slyderin', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'House',
            },
        ),
        migrations.CreateModel(
            name='PotionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PotionStatus',
            },
        ),
    ]
