# Generated by Django 5.2.7 on 2025-10-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_item_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
                ('itemPrice', models.IntegerField()),
                ('itemShow', models.BooleanField()),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
    ]
