# Generated by Django 5.1.1 on 2024-11-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_house_potionstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potion',
            old_name='potionInfo',
            new_name='itemInfo',
        ),
        migrations.RenameField(
            model_name='potion',
            old_name='potion',
            new_name='itemName',
        ),
        migrations.AddField(
            model_name='potion',
            name='itemCategory',
            field=models.TextField(default='마법 약'),
        ),
    ]
