# Generated by Django 5.1.1 on 2025-10-06 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('charID', models.AutoField(primary_key=True, serialize=False)),
                ('charName', models.TextField()),
                ('charEngName', models.TextField()),
                ('charCatchPhrase', models.TextField()),
                ('charPhrase', models.TextField()),
                ('charImageInfo', models.TextField(null=True)),
                ('charCommission', models.BooleanField()),
                ('charCommissionInfo', models.TextField(null=True)),
                ('charRealm', models.TextField()),
                ('charSex', models.TextField()),
                ('charAge', models.IntegerField()),
                ('charSpecies', models.TextField()),
                ('charHeight', models.IntegerField()),
                ('charWeight', models.IntegerField()),
                ('charKeyword1', models.TextField()),
                ('charKeyword2', models.TextField()),
                ('charKeyword3', models.TextField()),
                ('charPersonality', models.TextField()),
                ('charPosition', models.TextField()),
                ('charHP', models.IntegerField()),
                ('charATK', models.IntegerField()),
                ('charDEF', models.IntegerField()),
                ('chaRES', models.IntegerField()),
                ('charLUK', models.IntegerField()),
                ('charEtc', models.TextField()),
                ('charSkill1', models.TextField()),
                ('charSkill2', models.TextField()),
                ('charSkill3', models.TextField()),
                ('charSkill1info', models.TextField()),
                ('charSkill2info', models.TextField()),
                ('charSkill3info', models.TextField()),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attendance', models.IntegerField(default=0)),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('broom_item_received', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GachaGift',
            fields=[
                ('giftID', models.AutoField(primary_key=True, serialize=False)),
                ('anonymous', models.BooleanField()),
                ('message', models.TextField(null=True)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('giver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given3', to=settings.AUTH_USER_MODEL)),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gacha')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received3', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gachagift',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('giftID', models.AutoField(primary_key=True, serialize=False)),
                ('anonymous', models.BooleanField()),
                ('message', models.TextField(null=True)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('giver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given', to=settings.AUTH_USER_MODEL)),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gift',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Inventory_gacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gacha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_gacha',
            },
        ),
        migrations.CreateModel(
            name='Inventory_magic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item_magic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_magic',
            },
        ),
        migrations.CreateModel(
            name='Inventory_potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.potion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_potion',
            },
        ),
        migrations.CreateModel(
            name='Inventory_ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_ring',
            },
        ),
        migrations.CreateModel(
            name='MagicGift',
            fields=[
                ('giftID', models.AutoField(primary_key=True, serialize=False)),
                ('anonymous', models.BooleanField()),
                ('message', models.TextField(null=True)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('giver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given2', to=settings.AUTH_USER_MODEL)),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item_magic')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'magicgift',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseID', models.AutoField(primary_key=True, serialize=False)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
