# Generated by Django 5.1.1 on 2025-10-20 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('charID', models.AutoField(primary_key=True, serialize=False)),
                ('charName', models.TextField()),
                ('charEngName', models.TextField()),
                ('charCatchPhrase', models.TextField()),
                ('charPhrase', models.TextField()),
                ('charImageInfo', models.TextField(null=True)),
                ('charCommission', models.BooleanField()),
                ('charCommissionInfo', models.TextField(null=True)),
                ('charRealm', models.TextField()),
                ('charSex', models.TextField()),
                ('charAge', models.IntegerField()),
                ('charSpecies', models.TextField()),
                ('charHeight', models.IntegerField()),
                ('charWeight', models.IntegerField()),
                ('charKeyword1', models.TextField()),
                ('charKeyword2', models.TextField()),
                ('charKeyword3', models.TextField()),
                ('charPersonality', models.TextField()),
                ('charPosition', models.TextField()),
                ('charHP', models.IntegerField()),
                ('charATK', models.IntegerField()),
                ('charDEF', models.IntegerField()),
                ('chaRES', models.IntegerField()),
                ('charLUK', models.IntegerField()),
                ('charEtc', models.TextField()),
                ('charSkill1', models.TextField()),
                ('charSkill2', models.TextField()),
                ('charSkill3', models.TextField()),
                ('charSkill1info', models.TextField()),
                ('charSkill2info', models.TextField()),
                ('charSkill3info', models.TextField()),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('giftID', models.AutoField(primary_key=True, serialize=False)),
                ('anonymous', models.BooleanField()),
                ('message', models.TextField(null=True)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gift',
            },
        ),
        migrations.CreateModel(
            name='IngredientGift',
            fields=[
                ('giftID', models.AutoField(primary_key=True, serialize=False)),
                ('anonymous', models.BooleanField()),
                ('message', models.TextField(null=True)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ingredientgift',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Inventory_ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
            ],
            options={
                'db_table': 'Inventory_ingredient',
            },
        ),
        migrations.CreateModel(
            name='Inventory_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCount', models.IntegerField()),
            ],
            options={
                'db_table': 'Inventory_recipe',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseID', models.AutoField(primary_key=True, serialize=False)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='RecipeGift',
            fields=[
                ('giftID', models.AutoField(primary_key=True, serialize=False)),
                ('anonymous', models.BooleanField()),
                ('message', models.TextField(null=True)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'recipegift',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attendance', models.IntegerField(default=0)),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('broom_item_received', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
