# Generated by Django 5.1.1 on 2024-11-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='charProfileMusic',
            field=models.TextField(null=True),
        ),
    ]
