# Generated by Django 5.1.1 on 2025-10-20 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('store', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='giver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given', to='users.charinfo'),
        ),
        migrations.AddField(
            model_name='gift',
            name='itemInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AddField(
            model_name='gift',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to='users.charinfo'),
        ),
        migrations.AddField(
            model_name='ingredientgift',
            name='giver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given2', to='users.charinfo'),
        ),
        migrations.AddField(
            model_name='ingredientgift',
            name='itemInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientgift',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received2', to='users.charinfo'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='itemInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory_ingredient',
            name='itemInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ingredient'),
        ),
        migrations.AddField(
            model_name='inventory_ingredient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory_recipe',
            name='itemInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.recipe'),
        ),
        migrations.AddField(
            model_name='inventory_recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='itemInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipegift',
            name='giver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given3', to='users.charinfo'),
        ),
        migrations.AddField(
            model_name='recipegift',
            name='itemInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.recipe'),
        ),
        migrations.AddField(
            model_name='recipegift',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received3', to='users.charinfo'),
        ),
    ]
