# Generated by Django 5.1.1 on 2025-10-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='charProfileMusic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
