# Generated by Django 5.1.1 on 2024-11-12 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_attendance_attendance_date'),
        ('store', '0004_house_potionstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicGift',
            fields=[
                ('giftID', models.AutoField(primary_key=True, serialize=False)),
                ('anonymous', models.BooleanField()),
                ('message', models.TextField(null=True)),
                ('itemCount', models.IntegerField()),
                ('orderDate', models.DateField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('giver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given2', to=settings.AUTH_USER_MODEL)),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item_magic')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'magicgift',
            },
        ),
    ]
