# Generated by Django 5.1.1 on 2025-10-20 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='챕터 제목')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='부제')),
                ('chapter_number', models.PositiveIntegerField(verbose_name='챕터 번호')),
                ('story_type', models.CharField(choices=[('main', '메인'), ('sub', '서브')], default='main', max_length=10, verbose_name='스토리 타입')),
                ('summary', models.TextField(verbose_name='줄거리 요약')),
                ('background_image', models.ImageField(upload_to='story_backgrounds/', verbose_name='스토리 배경 이미지')),
                ('list_image', models.ImageField(upload_to='chapter_thumbnails/', verbose_name='챕터 목록 이미지')),
            ],
        ),
        migrations.CreateModel(
            name='LogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='퀘스트 제목')),
                ('description', models.TextField(verbose_name='상세 내용')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='시작일')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='기한 (일)')),
                ('reward_gold', models.PositiveIntegerField(default=0, verbose_name='보상 골드')),
            ],
        ),
        migrations.CreateModel(
            name='QuestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='게시글 제목')),
                ('content', models.TextField(verbose_name='로그 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quest_logs/', verbose_name='첨부 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestRewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
            ],
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=100, verbose_name='화자 이름')),
                ('text', models.TextField(verbose_name='대사 내용')),
                ('order', models.PositiveIntegerField(verbose_name='순서')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_lines', to='main.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
