# Generated by Django 5.1.1 on 2025-10-20 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('member', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questlog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_logs', to='member.characters'),
        ),
        migrations.AddField(
            model_name='questlog',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.quest'),
        ),
        migrations.AddField(
            model_name='logcomment',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.questlog'),
        ),
        migrations.AddField(
            model_name='questrewarditem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ingredient'),
        ),
        migrations.AddField(
            model_name='questrewarditem',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='reward_items',
            field=models.ManyToManyField(blank=True, related_name='quests', through='main.QuestRewardItem', to='store.ingredient'),
        ),
    ]
